package corbaBanque;


/**
* corbaBanque/IBanqueRemoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banque.idl
* mardi 21 janvier 2025 04 h 08 CET
*/

public interface IBanqueRemoteOperations 
{
  double conversion (double mt);
  corbaBanque.Compte getCompte (int code);
  corbaBanque.Compte[] getComptes ();
} // interface IBanqueRemoteOperations
